import { fetchAsHTML} from '../fetch.js';

function fetchAllmusicTags(url, entity){
    return fetchAsHTML(url)
        .then((html) => {
            let tags = [];
            const pushTag = (aElement) => {
                for(const tag of translateAllmusicTag(aElement.textContent))
                    tags.push(tag);
            }
            html.querySelectorAll(".genre a").forEach(pushTag);
            html.querySelectorAll(".styles a").forEach(pushTag);
            return tags;
        });
}

const allmusicGenresNotInMBzMap = {
    "aboriginal rock": "aboriginal rock, rock",
    "acid folk": "acid folk, acid, folk",
    "acoustic louisiana blues": "acoustic louisiana blues, acoustic blues",
    "acoustic memphis blues": "acoustic memphis blues, acoustic blues",
    "acoustic new orleans blues": "acoustic new orleans blues, acoustic blues",
    "adult alternative pop/rock": "adult aternative pop rock, alternative pop rock, pop rock",
    "adult alternative": "adult alternative, alternative",
    "adult contemporary r&b": "adult contemporary r&b, contemporary r&b",
    "adult contemporary": "adult contemporary, contemporary",
    "afoxe": "afoxê",
    "african folk": "african folk, afro-folk, folk",
    "african jazz": "afro-jazz",
    "african psychedelia": "african psychedelia, african psychedelic, psychedelic",
    "afro-beat": "afrobeat",
    "al-jil": "al jeel",
    "alt-country": "alternative country",
    "alterna movimiento": "movimiento alterado",
    "alternative ccm": "contemporary christian, alternative, alternative contemporary christian",
    "alternative corridos": "alternative corrido, alternative, corrido",
    "alternative country-rock": "alternative country rock, alternative rock, alternative country, country rock",
    "alternative latin": "alternative latin, latin",
    "alternative pop/rock": "alternative pop rock, pop rock",
    "alternative rap": "alternative hip hop",
    "alternative singer/songwriter": "alternative singer-songwriter, singer-songwriter, alternative",
    "alternative/indie rock": "alternative rock, indie rock",
    "am pop": "am pop, pop",
    "ambient breakbeat": "ambient breakbeat, ambient, breakbeat",
    "american jewish pop": "american jewish pop, pop",
    "american popular song": "american popular song, pop",
    "american punk": "american punk, punk",
    "american trad rock": "american trad rock, trad rock, traditional rock, rock",
    "anarchist punk": "anarcho-punk",
    "andalus classical": "andalusian classical, classical",
    "andean folk": "andean folk, folk",
    "appalachian": "appalachian folk",
    "argentinian folk": "argentinian folk, folk",
    "armenian folk": "armenian folk, folk",
    "asian folk": "asian folk, folk",
    "asian pop": "asian pop, pop",
    "asian psychedelia": "asian psychedelia, psychedelic, psychedelia",
    "asian rap": "asian rap, hip-hop",
    "asian rock": "asian rock, rock",
    "aussie rock": "aussie rock, rock",
    "austropop": "austropop, pop",
    "avant-garde music": "avant-garde",
    "axe": "axé",
    "band music": "concert band",
    "barbershop quartet": "barbershop",
    "baseline": "bassline",
    "bay area rap": "bay area hip hop, hip hop, west coast hip hop",
    "beach": "beach music",
    "bird calls": "birdsong",
    "black gospel": "traditional black gospel, black gospel",
    "bluegrass-gospel": "bluegrass gospel",
    "blues gospel": "blues gospel, blues, gospel",
    "blues revival": "blues revival, blues",
    "blues-rock": "blues rock",
    "bop vocals": "bebop vocals",
    "bop": "bebop",
    "brazilian folk": "brazilian folk, folk",
    "brazilian jazz": "brazilian jazz, jazz",
    "brazilian pop": "brazilian pop, pop",
    "british dance bands": "british dance bands, dance",
    "british folk": "british folk, folk",
    "british folk-rock": "british folk-rock, folk rock",
    "british metal": "british metal, metal",
    "british psychedelia": "british psychedelia, psychedelic",
    "british punk": "british punk, punk",
    "british rap": "british hip hop, hip hop",
    "british trad rock": "british trad rock, trad rock, traditonal rock, rock",
    "buddhist": "tibetan buddhist chant",
    "bulgarian folk": "bulgarian folk, folk",
    "c-86": "c86",
    "carnatic": "carnatic classical",
    "celtic folk": "celtic folk, folk, celtic",
    "celtic gospel": "celtic gospel, gospel, celtic",
    "celtic pop": "celtic pop, pop, celtic",
    "cha-cha": "chachachá",
    "chamber jazz": "chamber jazz, jazz",
    "changui": "changüí",
    "chicago jazz": "chicago jazz, jazz",
    "children's folk": "children's folk, children's music, folk",
    "children's pop": "children's pop, children's music, pop",
    "children's rock": "children's rock, children's music, rock",
    "children's songwriters": "children's songwriters, children's music, singer-songwriter",
    "children's": "children's music",
    "chiptunes": "chiptune",
    "christian comedy": "christian comedy, comedy",
    "christian rap": "christian hip hop",
    "christmas": "christmas music",
    "classic blues vocals": "classic blues vocals, classic blues",
    "classic female blues": "classic female blues, classic blues",
    "classical pop": "classical pop, classical, pop",
    "club/dance": "club, dance",
    "cocktail": "cocktail nation",
    "cold wave": "coldwave",
    "college rock": "college rock, rock",
    "comedy rap": "comedy hip hop",
    "comedy/spoken": "standup comedy",
    "contemporary bluegrass": "contemporary bluegrass, bluegrass",
    "contemporary blues": "contemporary blues, blues",
    "contemporary celtic": "contemporary celtic, celtic",
    "contemporary flamenco": "contemporary flamenco, flamenco",
    "contemporary instrumental": "contemporary instrumental, instrumental",
    "contemporary jazz vocals": "contemporary jazz vocals, vocal jazz, contemporary jazz",
    "contemporary native american": "contemporary native american",
    "contemporary pop/rock": "contemporary pop rock, pop rock",
    "contemporary rap": "contemporary hip hop, hip hop",
    "contemporary reggae": "contemporary reggae, reggae",
    "contemporary singer/songwriter": "contemporary singer-songwriter, singer-songwriter",
    "continental jazz": "continental jazz, jazz",
    "cool": "cool jazz",
    "country & irish": "country and irish",
    "country comedy": "country comedy, country",
    "country-folk": "country folk",
    "country-pop": "country pop",
    "country-rock": "country rock",
    "creative orchestra": "creative orchestra, orchestral",
    "cuban jazz": "cuban jazz, jazz",
    "cuban pop": "cuban pop, pop",
    "dance bands": "dance bands, dance",
    "danzon": "danzón",
    "darkwave": "dark wave",
    "deep funk revival": "deep funk revival, deep funk",
    "detroit blues": "detroit blues, blues",
    "detroit rock": "detroit rock, rock",
    "dirty blues": "dirty blues, blues",
    "dirty rap": "dirty hip hop, hip hop",
    "dj/toasting": "toasting, reggae",
    "doo wop": "doo-wop",
    "drill'n'bass": "drill and bass",
    "dutch pop": "dutch pop, pop",
    "early american blues": "early american blues, blues",
    "early british pop/rock": "early british pop rock, british pop rock, pop rock",
    "early country": "early country, country",
    "early creative": "early creative, creative",
    "early jazz vocals": "early jazz vocals, vocal jazz",
    "early jazz": "early jazz, jazz",
    "early pop/rock": "early pop rock, pop rock",
    "early r&b": "early r&b, r&b",
    "east coast blues": "east coast blues, blues",
    "east coast rap": "east coast hip hop",
    "eastern european pop": "eastern european pop, pop",
    "easy pop": "easy pop, pop",
    "electric chicago blues": "electric chicago blues, chicago blues, electric blues",
    "electric country blues": "electric country blues, country blues, electric blues",
    "electric delta blues": "electric delta blues, delta blues, electric blues",
    "electric harmonica blues": "electric harmonica blues, blues, electric blues",
    "electric jazz": "electric jazz, jazz",
    "electric memphis blues": "electric memphis blues, electric blues",
    "electro-acoustic": "electroacoustic",
    "electro-cumbia": "electro-cumbia, cumbia",
    "electro-jazz": "electro-jazz, jazz",
    "electro-techno": "electro-techno, techno",
    "electronic/computer music": "electronic, computer music",
    "emo-pop": "emo pop",
    "ethiopian pop": "ethiopian pop, pop",
    "ethnic comedy": "ethnic comedy, comedy",
    "euro-dance": "eurodance",
    "euro-pop": "europop",
    "euro-rock": "euro-rock, rock",
    "european folk": "european folk, folk",
    "european psychedelia": "european psychedelia, psychedelic",
    "european rap": "european hip hop, hip hop",
    "experimental ambient": "experimental ambient, experimental, ambient",
    "experimental club": "experimental club, experimental, club",
    "experimental dub": "experimental dub, experimental, dub",
    "experimental electro": "experimental electro, experimental, electro",
    "experimental jungle": "experimental jungle, experimental, jungle",
    "experimental techno": "experimental techno, experimental, techno",
    "field recordings": "field recording",
    "finnish folk": "finnish folk, folk",
    "flute/new age": "flute, new age",
    "folk dance": "folk dance, folk",
    "folk jazz": "folk jazz, folk, jazz",
    "folk revival": "folk revival",
    "folk-blues": "folk blues, folk, blues",
    "folk-metal": "folk metal, folk, metal",
    "folk-pop": "folk pop",
    "folk-rock": "folk rock",
    "folklore": "folklore",
    "folksongs": "folk",
    "free funk": "free funk",
    "french chanson": "chanson française",
    "french folk": "french folk, folk",
    "french pop": "french pop, pop",
    "french rap": "french hip hop, hip hop",
    "french rock": "french rock, rock",
    "gabba": "gabba, hardcore techno",
    "garage": "garage house",
    "gay comedy": "gay comedy, comedy",
    "german rap": "german hip hop, hip hop",
    "giddha": "giddha, indian classical",
    "glitter": "glitter, glam rock, hard rock",
    "global jazz": "global jazz, jazz",
    "gospel choir": "gospel choir, gospel",
    "goth metal": "gothic metal",
    "goth rock": "gothic rock",
    "greek folk": "greek folk, folk",
    "greek-pop": "greek pop, pop",
    "grunge revival": "grunge revival, grunge",
    "grupero": "grupero, latin",
    "guitar jazz": "guitar jazz, jazz",
    "guitar/easy listening": "easy listening",
    "guitar/new age": "new age, guitar",
    "gypsy": "romani",
    "hair metal": "hair metal, metal",
    "hardcore rap": "hardcore hip hop",
    "harmonica blues": "harmonica blues, blues",
    "harmony vocal group": "harmony vocal group, minstrelsy",
    "harp/new age": "new age, harp",
    "horror rap": "horror hip hop, hip hop",
    "hot jazz": "hot jazz, jazz",
    "hot rod revival": "hot rod revival, hot rod",
    "hungarian folk": "hungarian folk, folk",
    "indie electronic": "indietronica",
    "indipop": "indian pop",
    "industrial dance": "industrial dance, industrial, dance",
    "industrial drum'n'bass": "industrial drum and bass, industrial, drum and bass",
    "instrumental children's music": "instrumental children's music, instrumental, children's music",
    "instrumental collections": "instrumental collections, instrumental",
    "instrumental country": "instrumental country, country",
    "instrumental gospel": "instrumental gospel, gospel",
    "instrumental hip-hop": "instrumental hip hop, hip hop",
    "instrumental pop": "instrumental pop, pop",
    "international folk": "international folk, folk",
    "international fusion": "international fusion",
    "international pop": "international pop, pop",
    "iran-classical": "iran-classical, iranian, classical",
    "islamic": "islamic modal music",
    "israeli jazz": "israeli jazz, jazz",
    "italian folk": "italian folk, folk",
    "italian music": "italian",
    "italian pop": "italian pop, pop",
    "italian rap": "italian hip hop, hip hop",
    "italo disco": "italo-disco",
    "jam bands": "jam band",
    "japanese orchestral": "japanese orchestral, orchestral, japanese",
    "japanese rap": "japanese hip hop, hip hop",
    "japanese rock": "japanese rock, rock",
    "jazz instrument": "jazz instrument, jazz",
    "jazz-house": "jazz house",
    "jazz-pop": "jazz pop",
    "jazz-rap": "jazz rap",
    "jazz-rock": "jazz rock",
    "jesus rock": "jesus music",
    "jewish folk": "jewish folk, folk",
    "jewish music": "jewish music",
    "jive": "jive, swing",
    "juju": "jùjú",
    "juke joint blues": "juke joint blues, r&b, blues",
    "juke/footwork": "juke, footwork",
    "jungle/drum'n'bass": "jungle",
    "keyboard/synthesizer/new age": "keyboard, synthesizer, new age",
    "korean rap": "korean hip hop, hip hop",
    "korean rock": "korean rock, rock",
    "l.a. punk": "los angeles punk, punk",
    "latin big band": "latin big band, latin, big band",
    "latin ccm": "latin contemporary christian, contemporary christian",
    "latin comedy": "latin comedy, latin, comedy",
    "latin dance": "latin dance, latin, dance",
    "latin folk": "latin folk, latin, folk",
    "latin freestyle": "latin freestyle, latin, freestyle",
    "latin gospel": "latin gospel, latin, gospel",
    "latin psychedelia": "latin psychedelia, psychedelic",
    "latin rap": "latin hip hop, latin, hip hop",
    "lds music": "lds music, mormon, contemporary christian",
    "left-field house": "leftfield house, leftfield, house",
    "left-field pop": "leftfield pop, leftfield, pop",
    "left-field rap": "leftfield hip hop, leftfield, hip hop",
    "macapat poetry": "macapat poetry, poetry",
    "mainstream jazz": "mainstream jazz, jazz",
    "mantras": "mantra",
    "marches": "march",
    "mbuti choral": "mbuti choral, choral",
    "meditation/relaxation": "meditation and relaxation",
    "memphis blues": "memphis blues, blues",
    "memphis soul": "memphis soul, soul",
    "mexican-cumbia": "cumbia mexicana",
    "middle eastern pop": "middle eastern pop, pop",
    "midwest rap": "midwest hip hop, hip hop",
    "mini jazz": "mini jazz, jazz",
    "minstrel": "minstrelsy",
    "miscellaneous (classical)": "classical",
    "modal music": "modal jazz",
    "modern acoustic blues": "modern acoustic blues, acoustic blues",
    "modern big band": "modern big band, big band",
    "modern delta blues": "modern delta blues, delta blues, modern blues",
    "modern electric blues": "modern electric blues, electric blues, modern blues",
    "modern electric chicago blues": "modern electric chicago blues, modern blues, electric blues",
    "modern electric texas blues": "modern electric texas blues, modern blues, elecric texas blues",
    "modern free": "modern free, free jazz",
    "modern jazz vocals": "modern jazz vocals, vocal jazz",
    "modern jazz": "modern jazz, jazz",
    "modern son": "modern son, latin",
    "mood music": "mood music, easy listening",
    "mugam": "muğam",
    "music comedy": "music comedy, comedy",
    "musical theater": "musical",
    "musicals": "musical",
    "musique actuelle": "musique actuelle, avant-garde",
    "mystical minimalism": "mystical minimalism, minimalism",
    "narcocorridos": "narcocorrido",
    "nashville sound/countrypolitan": "nashville sound, countrypolitan",
    "nature": "nature sounds",
    "ndombolo": "ndombolo",
    "neo-bop": "neo-bebop, bebop",
    "neo-classical metal": "neoclassical metal",
    "neo-classical": "neoclassical",
    "neo-disco": "neo-disco",
    "neo-electro": "neo-electro",
    "neo-glam": "neo-glam",
    "neo-prog": "neo-progressive rock",
    "neo-soul": "neo soul",
    "neo-traditional folk": "neo-traditional folk",
    "neo-traditional": "neo-traditional",
    "neo-traditionalist country": "neo-traditionalist country",
    "new age tone poems": "new age tone poems, new age",
    "new orleans brass bands": "new orleans brass bands, jazz",
    "new orleans jazz revival": "new orleans jazz revival, jazz",
    "new orleans jazz": "new orleans jazz, jazz",
    "new traditionalist": "new traditionalist, country",
    "new wave of british heavy metal": "new wave british heavy metal, new wave, heavy metal",
    "new wave/post-punk revival": "new wave, post-punk revival",
    "new york blues": "new york blues, blues",
    "new york punk": "new york punk, punk",
    "new york salsa": "new york salsa, salsa",
    "new zealand rock": "new zealand rock, rock",
    "newbeat": "newbeat, acid house",
    "noise-rock": "noise rock",
    "norteno": "norteño",
    "norwegian folk": "norwegian folk, folk",
    "novelty ragtime": "novelty piano",
    "nursery rhymes": "nursery rhymes, children's music",
    "nyahbinghi": "nyahbinghi, reggae",
    "nü metal": "nu metal",
    "obscuro": "obscuro, psychedelic",
    "observational humor": "observational humor, comedy",
    "occasion-based effects": "occasion-based effects, sound effects",
    "oi!": "oi",
    "okinawan pop": "okinawan pop, pop",
    "old-school rap": "old school hip hop",
    "old-timey": "old-time",
    "orchestral/easy listening": "orchestral, easy listening",
    "organ/easy listening": "organ, easy listening",
    "panflute/easy listening": "panflute, easy listening",
    "party rap": "party rap, hip hop",
    "peruvian folk": "peruvian folk, folk",
    "piano jazz": "piano, jazz",
    "piano/easy listening": "piano, easy listening",
    "piano/new age": "piano, new age",
    "pipe bands": "pipe band music",
    "political comedy": "political comedy, comedy",
    "political folk": "political folk, folk",
    "political rap": "political hip hop, hip hop",
    "political reggae": "political reggae, reggae",
    "pop-metal": "pop metal",
    "pop-rap": "pop rap",
    "pop-soul": "pop soul",
    "pop/rock": "pop rock",
    "post-disco": "post-disco",
    "pre-war blues": "pre-war blues, blues",
    "pre-war country blues": "pre-war country blues, country blues",
    "pre-war gospel blues": "pre-war gospel blues, gospel, blues",
    "process-generated": "process music",
    "prog-rock": "progressive rock",
    "progressive alternative": "progressive alternative, progressive",
    "progressive big band": "progressive big band",
    "progressive jazz": "progressive jazz",
    "psychedelic/garage": "psychedelic, garage psych",
    "punk metal": "punk metal, punk",
    "punk revival": "punk revival, punk",
    "punk/new wave": "punk, new wave",
    "r&b instrumental": "r&b, instrumental",
    "raga": "raga, indian classical",
    "rai": "raï",
    "rap-metal": "rap metal",
    "rap-rock": "rap rock",
    "reggae gospel": "reggae gospel, reggae, gospel",
    "regional blues": "regional blues, blues",
    "retro swing": "retro swing, swing",
    "retro-rock": "retro-rock, rock",
    "retro-soul": "retro-soul, soul",
    "rock & roll": "rock and roll",
    "rock en español": "rock en español, rock",
    "rockabilly revival": "rockabilly revival, rockabilly",
    "russian folk": "russian folk, folk",
    "satire": "satire, comedy",
    "saxophone jazz": "saxophone, jazz",
    "scandinavian metal": "scandinavian metal, metal",
    "scandinavian pop": "scandinavian pop, pop",
    "scottish country dance": "scottish country dance music",
    "scottish folk": "scottish folk, folk",
    "sea shanties": "sea shanty",
    "sha'abi": "shaabi",
    "show tunes": "show tunes, musical",
    "show/musical": "musical",
    "sing-alongs": "sing-along",
    "singer/songwriter": "singer-songwriter",
    "ska revival": "ska revival, ska",
    "ska-punk": "ska punk",
    "skatepunk": "skate punk",
    "slide guitar blues": "slide guitar blues, blues",
    "smooth reggae": "smooth reggae, reggae",
    "social media pop": "social media pop, pop",
    "society dance band": "society dance band, dance band",
    "solo instrumental": "solo instrumental",
    "son": "son cubano",
    "song parody": "parody",
    "soul-blues": "soul blues",
    "south african folk": "south african folk, folk",
    "south african pop": "south african pop, pop",
    "southern rap": "southern hip hop",
    "spanish folk": "spanish folk, folk",
    "speeches": "speech",
    "speed/thrash metal": "speed metal, thrash metal",
    "spoken comedy": "spoken comedy, comedy",
    "st. louis blues": "st louis blues, blues",
    "standards": "jazz standard, jazz",
    "straight-ahead jazz": "straight-ahead jazz, jazz",
    "straight-edge": "straight-edge",
    "string bands": "string bands",
    "structured improvisation": "structured improvisation, improvisation",
    "surf revival": "surf revival, surf",
    "swedish folk": "swedish folk, folk",
    "swedish pop/rock": "swedish pop rock, pop rock",
    "swiss folk": "swiss folk, folk",
    "tech-house": "tech house",
    "techno-dub": "techno dub, techno, dub, minimalism",
    "texas rap": "texas hip hop, hip hop",
    "thai pop": "thai pop, pop",
    "third wave ska revival": "third wave ska",
    "tin pan alley pop": "tin pan alley",
    "township jazz": "township jazz, jazz",
    "trad jazz": "traditional jazz, jazz",
    "traditional blues": "traditional blues, blues",
    "traditional celtic": "traditional celtic, celtic",
    "traditional chinese": "traditional chinese, chinese classical",
    "traditional european folk": "traditional european folk, folk",
    "traditional folk": "traditional folk, folk",
    "traditional gospel": "traditional gospel, gospel",
    "traditional irish folk": "traditional irish folk, irish folk",
    "traditional japanese": "traditional japanese, japanese classical",
    "traditional korean": "traditional korean, korean classical",
    "traditional middle eastern folk": "traditional middle eastern folk, folk",
    "traditional native american": "traditional native american",
    "traditional scottish folk": "traditional scottish folk, folk",
    "trap (edm)": "trap edm",
    "trap (latin)": "trap latino",
    "trap (rap)": "trap hip hop, trap, hip hop",
    "trip-hop": "trip hop",
    "trombone jazz": "trombone, jazz",
    "tropicalia": "tropicália",
    "trumpet jazz": "trumpet, jazz",
    "trumpet/easy listening": "trumpet, easy listening",
    "turkish psychedelia": "turkish psychedelia, psychedelic",
    "underground rap": "underground hip hop",
    "uptown soul": "uptown soul, soul",
    "urban blues": "urban blues, blues",
    "urban folk": "urban folk, folk",
    "vibraphone/marimba jazz": "vibraphone, marimba, jazz",
    "vocal pop": "vocal pop, pop",
    "volksmusik": "volkstümliche musik",
    "west coast blues": "west coast blues, blues",
    "west coast jazz": "west coast jazz, jazz",
    "west coast rap": "west coast hip hop",
    "western swing revival": "western swing revival, western swing",
    "work songs": "work song",
    "yodel": "yodeling",
}

function translateAllmusicTag(tag){
    if(allmusicGenresNotInMBzMap[tag]){
	return allmusicGenresNotInMBzMap[tag].split("\w*,\w*");
    }else{
	console.log(`genre not found: "${tag}"`);
	return new Array(tag);
    }

}

export const allmusic = { domain: "allmusic.com",
                          fetchTags: fetchAllmusicTags,
                          supportedTypes: ["artist", "release-group"],
                          name: "AllMusic",
                          faviconClass: "allmusic-favicon",}
